### ISSUE TITLE
GitLab: Ignoring of internal bot users not working for group tokens

### ISSUE THREAD

**Issue by MisterTNT** [vaulttec/idm-sync#16]
Dear project members,

we just found out that group tokens seem not to fit in the rules for ignoring and are blocked on a regular basis. Project and personal tokens still work as intended.

We use GitLab EE 15.3.4.

Please fix.

Kind Regards,

Thomas

**Comment by tjuerge** [comment]
Thomas, you're right. The fixes in #14 are only recognizing the project access tokens (by username pattern). So yes, we need a solution for group access tokens as well.

It seems that [GitLab API's user object](https://docs.gitlab.com/ee/api/users.html#for-user) has an "bot" attribute now. And the [user search API](https://docs.gitlab.com/ee/api/users.html#for-normal-users) seems to support excluding bot users as well (via `GET /users?without_project_bots=true`).
